obstacles:
  # 锯齿形障碍物 - 移动到机器人可达范围内
  - shape: segment
    points: [[500, 500], [550, 550]]
  - shape: segment
    points: [[550, 550], [600, 500]]
  - shape: segment
    points: [[600, 500], [650, 550]]
  - shape: segment
    points: [[650, 550], [700, 500]]
  
  - shape: segment
    points: [[500, 600], [550, 650]]
  - shape: segment
    points: [[550, 650], [600, 600]]
  - shape: segment
    points: [[600, 600], [650, 650]]
  - shape: segment
    points: [[650, 650], [700, 600]]

goal:
  position: [600, 575]  # 目标也移动到障碍物中心附近
  radius: 10

start:
  position: [300, 550]  # 保持起始位置不变
  angle: 0
